### ISSUE TITLE
Will this plugin works when the app is in the background?

### ISSUE THREAD

**Issue by Bnaya** [MobileChromeApps/cordova-plugin-chrome-apps-gcm#1]
what will happen when there's incoming message but the app closed

**Comment by agrieve** [comment]
This plugin uses [cordova-plugin-background-app](https://github.com/MobileChromeApps/cordova-plugin-background-app) to enable it to run as a background service in that case. 

For mobile Chrome Apps, the background page will be loaded and the push event fired. For vanilla Cordova apps, deviceready will fire and then the event will fire. The cordova-plugin-background-app has a good [example](https://github.com/MobileChromeApps/cordova-plugin-background-app/blob/master/example-app/www/index.html) of how to use the plugin in a vanilla cordova app.
